# Generated by Django 5.1.4 on 2025-03-22 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='introsection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greeting_text', models.CharField(default='Hello friend!', max_length=255)),
                ('availability_text', models.CharField(default='I’m available for freelance work.', max_length=255)),
                ('profile_image', models.ImageField(default='cover.png', upload_to='media/profile')),
                ('hero_image', models.ImageField(default='default_hero.png', upload_to='media/coverImage')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Homepage introSection',
                'verbose_name_plural': 'Homepage introSection',
            },
        ),
    ]
