# Generated by Django 5.1.4 on 2025-03-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='introsection',
        ),
    ]
