# Generated by Django 5.1.4 on 2025-03-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overview_title', models.CharField(max_length=200)),
                ('overview_text', models.TextField()),
                ('education_title', models.CharField(max_length=200)),
                ('education_text', models.TextField()),
                ('work_experience_title', models.CharField(max_length=200)),
                ('work_experience_text', models.TextField()),
                ('personal_life_title', models.CharField(max_length=200)),
                ('personal_life_text', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
