# Generated by Django 5.1.4 on 2025-03-31 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_aboutme_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('years_of_experience', models.PositiveIntegerField()),
                ('happy_customers', models.PositiveIntegerField()),
                ('projects_finished', models.PositiveIntegerField()),
                ('digital_awards', models.PositiveIntegerField()),
            ],
        ),
    ]
